### ISSUE TITLE
When a `repeat` block is nested inside a `if` block, the generated code produces broken labels

### ISSUE THREAD

**Issue by haroldo-ok** [haroldo-ok/vcs-game-maker#109]
Original post: https://itch.io/post/11040422

## Assembled blocks:
![A0Vb9u](https://github.com/user-attachments/assets/94aec1dd-710d-44a1-ba37-a39cef136b38)

## Generated code:
![VQV4Gs](https://github.com/user-attachments/assets/0610ffc4-41d0-4bed-ba96-e3156713a487)

**Comment by Nolan0027** [comment]
Excited for fix

**Comment by haroldo-ok** [comment]
Code generation error reproduced: 
- This project: [bug-109-nested-repeat.zip](https://github.com/user-attachments/files/17284846/bug-109-nested-repeat.zip)
- Generates this malformed block:
```basic
  if 0 then goto _if_1 else goto _if_1_end
_if_1
while2start
  if collision(player0, missile0) then goto while2end
  player0x = player0x + 1

  goto while2start
while2end
  goto _if_1_else_end
_if_1_end
while2start
  if collision(player0, missile0) then goto while2end
  player0x = player0x + 1

  goto while2start
while2end@ _if_1_else_end
```

**Comment by Nolan0027** [comment]
Cool
