### ISSUE TITLE
"color" ? doesnt change color

### ISSUE THREAD

**Issue by zartan9** [haroldo-ok/vcs-game-maker#24]
hi dabbling in vcs maker again. what does setting color do to player 0? Also is there a way to go to another level/screen? Thanks!

**Comment by haroldo-ok** [comment]
It should be working, but, for some reason, it isn't...

**Comment by zartan9** [comment]
ah no problem###  my game doesnt really need color just wondering... to get different levels i download/generate a rom per "scene" change the background and generate a "level2" rom etc is how i make multiple levels! thanks

**Comment by haroldo-ok** [comment]
Yes, there are blocks planned for that, but they aren't implemented, yet:
- #21 would add blocks for resetting, increasing and decreasing the score;
- #16 would modify the background editor to allow having multiple backgrounds and add a block to select the background to use.

It also looks like #11 also mentions the current bug.
