### ISSUE TITLE
Game does not update no matter what I do

### ISSUE THREAD

**Issue by Samusaran2** [haroldo-ok/vcs-game-maker#36]
I'm trying to make a little thing with this application and it seems to work out pretty well. However, for some ungodly reason, now the generated ROM NEVER seems to manage to update no matter what I do. (The only way I've managed to get it to update is by deleting all the events, which obviously doesn't matter much since I can't save it after I put them back in)

**Comment by Samusaran2** [comment]
Actually, from what I'm seeing, it does not update if there are any variable-related events present in the game.

**Comment by Samusaran2** [comment]
Math as a whole seems broken, if the "variable" = "value" logic function is used in any condition, the whole game just breaks and does not update.

**Comment by haroldo-ok** [comment]
Hello; thanks for the bug report.
Could you please attach the exported project, so I could have a look, later?

**Comment by Samusaran2** [comment]
I have found a workaround (It seems to mostly be the equal and non-equal signs that don't work, along with the repeat functions for whatever reason) and am working on a cleaner version of the project now, but here's the old one so you can analyse what the hell is wrong here.

https://www.mediafire.com/file/mpz3vbe7hawpte0/project-2023-02-07-01-19-43.vcsgm/file

(Also, while we're talking here, it would be handy to be able to change the background color, just saying. And yes, this is a FNAF fangame, because what else do you do when you're given a block-based programming program?)

**Comment by haroldo-ok** [comment]
I tested it; for some reason, the "change variable" block is generating invalid bBasic code:

For some reason, this block:
![image](https://user-images.githubusercontent.com/1457465/217935412-243f43a1-8d9c-4817-b431-b84a008567b0.png)

Is generating this code:
```basic
 if joy0up then Timer = (typeof Timer == 'number' ? Timer : 0) + 1; : score = score + 1
```

It seems to be a bug on the code generation routine; I shall take a look at it later on.
