### ISSUE TITLE
RNG

### ISSUE THREAD

**Issue by Samusaran2** [haroldo-ok/vcs-game-maker#38]
Would be useful to have a RNG generator from a certain range that we want.

(Like "set (Variable) to RNG (1,20)" and it would generate a random number from 1 to 20)

**Comment by haroldo-ok** [comment]
That could be a good idea.

**Comment by Samusaran2** [comment]
Would be really useful for my current project.

**Comment by Samusaran2** [comment]
Has there been any progress on this?

**Comment by haroldo-ok** [comment]
So far, I've been doing other things, but I already know which bBasic command the block would have to use: 
https://www.randomterrain.com/atari-2600-memories-batari-basic-commands.html#rand

**Comment by haroldo-ok** [comment]
Also for future reference:
https://forums.atariage.com/topic/306068-random-numbers/
